# bash aliases
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi
PS1="\u > "
# Добавляем отображение ветки для репозитариев git
git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(git: \1 )/'
}

export PS1="\$(git_branch)> "
